namespace ColorControl.Shared.Contracts;

public static class VcpCodes
{
    public static readonly Dictionary<string, string> CodeList = new()
    {
        { "00", "VCP Code Page" },
        { "01", "Degauss" },
        { "02", "New Control Value" },
        { "03", "Soft Controls" },
        { "04", "Restore Factory Defaults" },
        { "05", "Restore Factory Luminance/ Contrast Defaults" },
        { "06", "Restore Factory Geometry Defaults" },
        { "07", "" },
        { "08", "Restore Factory Color Defaults" },
        { "09", "" },
        { "0A", "Restore Factory TV Defaults" },
        { "0B", "Color Temperature Increment" },
        { "0C", "Color Temperature Request" },
        { "0D", "" },
        { "0E", "Clock" },
        { "0F", "" },
        { "10", "Luminance" },
        { "11", "Flesh Tone Enhancement" },
        { "12", "Contrast" },
        { "13", "Backlight Control" },
        { "14", "Select Color Preset" },
        { "15", "" },
        { "16", "Video Gain (Drive): Red" },
        { "17", "User Color Vision Compensation" },
        { "18", "Video Gain (Drive): Green" },
        { "19", "" },
        { "1A", "Video Gain (Drive): Blue" },
        { "1B", "" },
        { "1C", "Focus" },
        { "1D", "" },
        { "1E", "Auto Setup" },
        { "1F", "Auto Color Setup" },
        { "20", "Horizontal Position (Phase)" },
        { "21", "" },
        { "22", "Horizontal Size" },
        { "23", "" },
        { "24", "Horizontal Pincushion" },
        { "25", "" },
        { "26", "Horizontal Pincushion Balance" },
        { "27", "" },
        { "28", "Horizontal Convergence R / B" },
        { "29", "Horizontal Convergence M / G" },
        { "2A", "Horizontal Linearity" },
        { "2B", "" },
        { "2C", "Horizontal Linearity Balance" },
        { "2D", "" },
        { "2E", "Gray Scale Expansion" },
        { "2F", "" },
        { "30", "Vertical Position (Phase)" },
        { "31", "" },
        { "32", "Vertical Size" },
        { "33", "" },
        { "34", "Vertical Pincushion" },
        { "35", "" },
        { "36", "Vertical Pincushion Balance" },
        { "37", "" },
        { "38", "Vertical Convergence R/B" },
        { "39", "Vertical Convergence M/G" },
        { "3A", "Vertical Linearity" },
        { "3B", "" },
        { "3C", "Vertical Linearity Balance" },
        { "3D", "" },
        { "3E", "Clock Phase" },
        { "3F", "" },
        { "40", "Horizontal Parallelogram" },
        { "41", "Vertical Parallelogram" },
        { "42", "Horizontal Keystone" },
        { "43", "Vertical Keystone" },
        { "44", "Rotation" },
        { "45", "" },
        { "46", "Top Corner Flare" },
        { "47", "" },
        { "48", "Top Corner Hook" },
        { "49", "" },
        { "4A", "Bottom Corner Flare" },
        { "4B", "" },
        { "4C", "Bottom Corner Hook" },
        { "4D", "" },
        { "4E", "" },
        { "4F", "" },
        { "50", "" },
        { "51", "" },
        { "52", "Active Control" },
        { "53", "" },
        { "54", "Performance Preservation" },
        { "55", "" },
        { "56", "H Moiré" },
        { "57", "" },
        { "58", "V Moiré" },
        { "59", "6 Axis Saturation Control: Red" },
        { "5A", "6 Axis Saturation Control: Yellow" },
        { "5B", "6 Axis Saturation Control: Green" },
        { "5C", "6 Axis Saturation Control: Cyan" },
        { "5D", "6 Axis Saturation Control: Blue" },
        { "5E", "6 Axis Saturation Control: Magenta" },
        { "5F", "" },
        { "60", "Input Select" },
        { "61", "" },
        { "62", "Audio: Speaker Volume" },
        { "63", "Audio: Speaker Pair Select" },
        { "64", "Audio: Microphone Volume" },
        { "65", "Audio: Jack Connection Status" },
        { "66", "Ambient Light Sensor" },
        { "67", "" },
        { "68", "" },
        { "69", "" },
        { "6A", "" },
        { "6B", "Backlight Level: White" },
        { "6C", "Video Black Level: Red" },
        { "6D", "Backlight Level: Red" },
        { "6E", "Video Black Level: Green" },
        { "6F", "Backlight Level: Green" },
        { "70", "Video Black Level: Blue" },
        { "71", "Backlight Level: Blue" },
        { "72", "Gamma" },
        { "73", "LUT Size" },
        { "74", "Single Point LUT Operation" },
        { "75", "Block LUT Operation" },
        { "76", "Remote Procedure Call" },
        { "77", "" },
        { "78", "Display Identification Data Operation" },
        { "79", "" },
        { "7A", "" },
        { "7B", "" },
        { "7C", "Adjust Zoom" },
        { "7D", "" },
        { "7E", "" },
        { "7F", "" },
        { "80", "" },
        { "81", "" },
        { "82", "Horizontal Mirror (Flip)" },
        { "83", "" },
        { "84", "Vertical Mirror (Flip)" },
        { "85", "" },
        { "86", "Display Scaling" },
        { "87", "Sharpness" },
        { "88", "Velocity Scan Modulation" },
        { "89", "" },
        { "8A", "Color Saturation" },
        { "8B", "TV Channel Up / Down" },
        { "8C", "TV Sharpness" },
        { "8D", "Audio Mute / Screen Blank" },
        { "8E", "TV Contrast" },
        { "8F", "Audio Treble" },
        { "90", "Hue" },
        { "91", "Audio Bass" },
        { "92", "TV Black Level / Luminance" },
        { "93", "Audio Balance L / R" },
        { "94", "Audio Processor Mode" },
        { "95", "" },
        { "96", "" },
        { "97", "" },
        { "98", "" },
        { "99", "" },
        { "9A", "Window Background" },
        { "9B", "6 Axis Color Control: Red" },
        { "9C", "6 Axis Color Control: Yellow" },
        { "9D", "6 Axis Color Control: Green" },
        { "9E", "6 Axis Color Control: Cyan" },
        { "9F", "6 Axis Color Control: Blue" },
        { "A0", "6 Axis Color Control: Magenta" },
        { "A1", "" },
        { "A2", "Auto Setup On / Off" },
        { "A3", "" },
        { "A4", "" },
        { "A5", "" },
        { "A6", "" },
        { "A7", "" },
        { "A8", "" },
        { "A9", "" },
        { "AA", "Screen Orientation" },
        { "AB", "" },
        { "AC", "Horizontal Frequency" },
        { "AD", "" },
        { "AE", "Vertical Frequency" },
        { "AF", "" },
        { "B0", "Settings" },
        { "B1", "" },
        { "B2", "Flat Panel Sub-Pixel Layout" },
        { "B3", "" },
        { "B4", "Source Timing Mode" },
        { "B5", "Source Color Coding" },
        { "B6", "Display Technology Type" },
        { "B7", "" },
        { "B8", "" },
        { "B9", "" },
        { "BA", "" },
        { "BB", "" },
        { "BC", "" },
        { "BD", "" },
        { "BE", "" },
        { "BF", "" },
        { "C0", "Display Usage Time" },
        { "C1", "" },
        { "C2", "Display Descriptor Length" },
        { "C3", "Transmit Display Descriptor" },
        { "C4", "Enable Display of ‘Display Descriptor’" },
        { "C5", "" },
        { "C6", "" },
        { "C7", "" },
        { "C8", "" },
        { "C9", "" },
        { "CA", "" },
        { "CB", "" },
        { "CC", "OSD Language" },
        { "CD", "Status Indicators" },
        { "CE", "" },
        { "CF", "" },
        { "D0", "Output Selection" },
        { "D1", "" },
        { "D2", "Asset Tag" },
        { "D3", "" },
        { "D4", "Stereo Video Mode" },
        { "D5", "" },
        { "D6", "Power Mode" },
        { "D7", "" },
        { "D8", "" },
        { "D9", "" },
        { "DA", "Scan Mode" },
        { "DB", "Image Mode" },
        { "DC", "Display Application" },
        { "DD", "" },
        { "DE", "" },
        { "DF", "VCP Version" },
        { "E0", "Manufacturer Specific" },
        { "E1", "Manufacturer Specific" },
        { "E2", "Manufacturer Specific" },
        { "E3", "Manufacturer Specific" },
        { "E4", "Manufacturer Specific" },
        { "E5", "Manufacturer Specific" },
        { "E6", "Manufacturer Specific" },
        { "E7", "Manufacturer Specific" },
        { "E8", "Manufacturer Specific" },
        { "E9", "Manufacturer Specific" },
        { "EA", "Manufacturer Specific" },
        { "EB", "Manufacturer Specific" },
        { "EC", "Manufacturer Specific" },
        { "ED", "Manufacturer Specific" },
        { "EE", "Manufacturer Specific" },
        { "EF", "Manufacturer Specific" },
        { "F0", "Manufacturer Specific" },
        { "F1", "Manufacturer Specific" },
        { "F2", "Manufacturer Specific" },
        { "F3", "Manufacturer Specific" },
        { "F4", "Manufacturer Specific" },
        { "F5", "Manufacturer Specific" },
        { "F6", "Manufacturer Specific" },
        { "F7", "Manufacturer Specific" },
        { "F8", "Manufacturer Specific" },
        { "F9", "Manufacturer Specific" },
        { "FA", "Manufacturer Specific" },
        { "FB", "Manufacturer Specific" },
        { "FC", "Manufacturer Specific" },
        { "FD", "Manufacturer Specific" },
        { "FE", "Manufacturer Specific" },
        { "FF", "Manufacturer Specific" }
    };
}
